var argv = require('minimist')(process.argv.slice(2));
var vfile = require('to-vfile')
var report = require('vfile-reporter')
var unified = require('unified')
var english = require('retext-english')
var stringify = require('retext-stringify')
var indefiniteArticle = require('retext-indefinite-article')
var readability  = require('retext-readability')
var passive   = require('retext-passive')
var repeatedWords  = require('retext-repeated-words')
var simplify = require('retext-simplify')
var nspell = require('nspell')
var dictionary = require('dictionary-en')
var spell  = require('retext-spell')

unified()
  .use(simplify)
  .use(readability)
  .use(passive)
  .use(english)
  .use(indefiniteArticle)
  .use(stringify)
  .process(vfile.readSync(argv[a]), function(err, file) {
    console.error(report(err || file))
  })
